// Code generated by sqlc. DO NOT EDIT.

package dal

import (
	"github.com/celer-network/goutils/big"
)

type Monitor struct {
	Key    string
	Blknum uint64
	Blkidx int64
}

type Nftxfer struct {
	CreatedAt int64
	SrcChid   uint64
	DstChid   uint64
	Sender    string
	Receiver  string
	SrcNft    string
	DstNft    string
	TokID     big.Int
	SrcTx     string
	DstTx     string
	Status    int16
}
