version: "3"

services:
  geth:
    container_name: geth
    image: "celer-network/geth"
    ports:
      - "8545-8546:8545-8546"
    volumes:
      - ./docker-volumes/geth-env:/geth/env:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.1

  geth2:
    container_name: geth2
    image: "celer-network/geth2"
    ports:
      - "8547-8548:8545-8546"
    volumes:
      - ./docker-volumes/geth2-env:/geth/env:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.6

  sgnnode0:
    container_name: sgnnode0
    image: "celer-network/sgnnode"
    ports:
      - "1317:1317"
      - "8081:8081"
      - "9090:9090"
      - "10000:10000"
      - "26656-26657:26656-26657"
    extra_hosts:
      - "api.coingecko.com:104.18.28.120"
    volumes:
      - ./docker-volumes/node0:/sgn-v2/env:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  sgnnode1:
    container_name: sgnnode1
    image: "celer-network/sgnnode"
    ports:
      - "26659-26660:26656-26657"
    volumes:
      - ./docker-volumes/node1:/sgn-v2/env:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  sgnnode2:
    container_name: sgnnode2
    image: "celer-network/sgnnode"
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./docker-volumes/node2:/sgn-v2/env:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  sgnnode3:
    container_name: sgnnode3
    image: "celer-network/sgnnode"
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./docker-volumes/node3:/sgn-v2/env:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

  crdb:
    container_name: crdb
    image: "celer-network/crdb"
    ports:
      - "26257:26257"
    networks:
      localnet:
        ipv4_address: 192.168.10.7

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/16
