[[multichain]]
chainID = 3
name = "ropsten"
gateway = "https://ropsten.infura.io/v3/c58bb2a63c1a466abb6d7b5e0b7b6828"
blkinterval = 15
blkdelay = 5
maxblkdelta = 5000
cbridge = "0x04Dd87EDDBE958C8f405e9c641693fAB94D562D1"
ksfile = "./test/keys/vsigner0.json"
kspass = ""

[[multichain]]
chainID = 5
name = "goerli"
gateway = "https://goerli.infura.io/v3/c58bb2a63c1a466abb6d7b5e0b7b6828"
blkinterval = 15
blkdelay = 5
maxblkdelta = 5000
cbridge = "0xC8CAf3c1D76D264B6D5d511d883B58b3874eAFa0"
ksfile = "./test/keys/vsigner0.json"
kspass = ""