// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sgn/health/v1/health.proto

package relayer

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ErrCode int32

const (
	ErrCode_ERROR_CODE_UNDEFINED                    ErrCode = 0
	ErrCode_ERROR_CODE_COMMON                       ErrCode = 500
	ErrCode_ERROR_NO_TOKEN_ON_DST_CHAIN             ErrCode = 1001
	ErrCode_ERROR_NO_TOKEN_ON_SRC_CHAIN             ErrCode = 1002
	ErrCode_ERROR_INIT_WITHDRAW_FAILED              ErrCode = 1003
	ErrCode_ERROR_CODE_NO_ENOUGH_TOKEN_ON_DST_CHAIN ErrCode = 1004
)

var ErrCode_name = map[int32]string{
	0:    "ERROR_CODE_UNDEFINED",
	500:  "ERROR_CODE_COMMON",
	1001: "ERROR_NO_TOKEN_ON_DST_CHAIN",
	1002: "ERROR_NO_TOKEN_ON_SRC_CHAIN",
	1003: "ERROR_INIT_WITHDRAW_FAILED",
	1004: "ERROR_CODE_NO_ENOUGH_TOKEN_ON_DST_CHAIN",
}

var ErrCode_value = map[string]int32{
	"ERROR_CODE_UNDEFINED":                    0,
	"ERROR_CODE_COMMON":                       500,
	"ERROR_NO_TOKEN_ON_DST_CHAIN":             1001,
	"ERROR_NO_TOKEN_ON_SRC_CHAIN":             1002,
	"ERROR_INIT_WITHDRAW_FAILED":              1003,
	"ERROR_CODE_NO_ENOUGH_TOKEN_ON_DST_CHAIN": 1004,
}

func (x ErrCode) String() string {
	return proto.EnumName(ErrCode_name, int32(x))
}

func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d6fdaa49c355133b, []int{0}
}

type ReportCurrentBlockNumberRequest struct {
	// serialized CurrentBlockNumberReport
	Report []byte `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	Sig    []byte `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
}

func (m *ReportCurrentBlockNumberRequest) Reset()         { *m = ReportCurrentBlockNumberRequest{} }
func (m *ReportCurrentBlockNumberRequest) String() string { return proto.CompactTextString(m) }
func (*ReportCurrentBlockNumberRequest) ProtoMessage()    {}
func (*ReportCurrentBlockNumberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6fdaa49c355133b, []int{0}
}
func (m *ReportCurrentBlockNumberRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ReportCurrentBlockNumberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ReportCurrentBlockNumberRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ReportCurrentBlockNumberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportCurrentBlockNumberRequest.Merge(m, src)
}
func (m *ReportCurrentBlockNumberRequest) XXX_Size() int {
	return m.Size()
}
func (m *ReportCurrentBlockNumberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportCurrentBlockNumberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReportCurrentBlockNumberRequest proto.InternalMessageInfo

func (m *ReportCurrentBlockNumberRequest) GetReport() []byte {
	if m != nil {
		return m.Report
	}
	return nil
}

func (m *ReportCurrentBlockNumberRequest) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

type CurrentBlockNumberReport struct {
	// in millis
	Timestamp uint64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// key is chainId, value is block number
	BlockNums   map[string]uint64 `protobuf:"bytes,2,rep,name=block_nums,json=blockNums,proto3" json:"block_nums,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	SgndVersion string            `protobuf:"bytes,3,opt,name=sgnd_version,json=sgndVersion,proto3" json:"sgnd_version,omitempty"`
}

func (m *CurrentBlockNumberReport) Reset()         { *m = CurrentBlockNumberReport{} }
func (m *CurrentBlockNumberReport) String() string { return proto.CompactTextString(m) }
func (*CurrentBlockNumberReport) ProtoMessage()    {}
func (*CurrentBlockNumberReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6fdaa49c355133b, []int{1}
}
func (m *CurrentBlockNumberReport) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CurrentBlockNumberReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CurrentBlockNumberReport.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CurrentBlockNumberReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrentBlockNumberReport.Merge(m, src)
}
func (m *CurrentBlockNumberReport) XXX_Size() int {
	return m.Size()
}
func (m *CurrentBlockNumberReport) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrentBlockNumberReport.DiscardUnknown(m)
}

var xxx_messageInfo_CurrentBlockNumberReport proto.InternalMessageInfo

func (m *CurrentBlockNumberReport) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *CurrentBlockNumberReport) GetBlockNums() map[string]uint64 {
	if m != nil {
		return m.BlockNums
	}
	return nil
}

func (m *CurrentBlockNumberReport) GetSgndVersion() string {
	if m != nil {
		return m.SgndVersion
	}
	return ""
}

type ReportCurrentBlockNumberResponse struct {
	Err *ErrMsg `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
}

func (m *ReportCurrentBlockNumberResponse) Reset()         { *m = ReportCurrentBlockNumberResponse{} }
func (m *ReportCurrentBlockNumberResponse) String() string { return proto.CompactTextString(m) }
func (*ReportCurrentBlockNumberResponse) ProtoMessage()    {}
func (*ReportCurrentBlockNumberResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6fdaa49c355133b, []int{2}
}
func (m *ReportCurrentBlockNumberResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ReportCurrentBlockNumberResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ReportCurrentBlockNumberResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ReportCurrentBlockNumberResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportCurrentBlockNumberResponse.Merge(m, src)
}
func (m *ReportCurrentBlockNumberResponse) XXX_Size() int {
	return m.Size()
}
func (m *ReportCurrentBlockNumberResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportCurrentBlockNumberResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReportCurrentBlockNumberResponse proto.InternalMessageInfo

func (m *ReportCurrentBlockNumberResponse) GetErr() *ErrMsg {
	if m != nil {
		return m.Err
	}
	return nil
}

type ErrMsg struct {
	Code ErrCode `protobuf:"varint,1,opt,name=code,proto3,enum=sgn.health.v1.ErrCode" json:"code,omitempty"`
	Msg  string  `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (m *ErrMsg) Reset()         { *m = ErrMsg{} }
func (m *ErrMsg) String() string { return proto.CompactTextString(m) }
func (*ErrMsg) ProtoMessage()    {}
func (*ErrMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6fdaa49c355133b, []int{3}
}
func (m *ErrMsg) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ErrMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ErrMsg.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ErrMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrMsg.Merge(m, src)
}
func (m *ErrMsg) XXX_Size() int {
	return m.Size()
}
func (m *ErrMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ErrMsg proto.InternalMessageInfo

func (m *ErrMsg) GetCode() ErrCode {
	if m != nil {
		return m.Code
	}
	return ErrCode_ERROR_CODE_UNDEFINED
}

func (m *ErrMsg) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterEnum("sgn.health.v1.ErrCode", ErrCode_name, ErrCode_value)
	proto.RegisterType((*ReportCurrentBlockNumberRequest)(nil), "sgn.health.v1.ReportCurrentBlockNumberRequest")
	proto.RegisterType((*CurrentBlockNumberReport)(nil), "sgn.health.v1.CurrentBlockNumberReport")
	proto.RegisterMapType((map[string]uint64)(nil), "sgn.health.v1.CurrentBlockNumberReport.BlockNumsEntry")
	proto.RegisterType((*ReportCurrentBlockNumberResponse)(nil), "sgn.health.v1.ReportCurrentBlockNumberResponse")
	proto.RegisterType((*ErrMsg)(nil), "sgn.health.v1.ErrMsg")
}

func init() { proto.RegisterFile("sgn/health/v1/health.proto", fileDescriptor_d6fdaa49c355133b) }

var fileDescriptor_d6fdaa49c355133b = []byte{
	// 513 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x4d, 0x8f, 0xd2, 0x50,
	0x14, 0x86, 0x29, 0x20, 0x84, 0xc3, 0x38, 0xc1, 0x9b, 0x91, 0x34, 0x68, 0x3a, 0xc8, 0x06, 0x32,
	0x71, 0x4a, 0x06, 0x13, 0x63, 0x8c, 0x1b, 0xa6, 0x2d, 0xd2, 0x20, 0xb7, 0xc9, 0x1d, 0x70, 0x12,
	0x37, 0x37, 0x7c, 0xdc, 0x14, 0x02, 0x6d, 0xf1, 0xde, 0x16, 0xc3, 0xbf, 0xf0, 0x67, 0xb9, 0x32,
	0xb3, 0x74, 0x69, 0x60, 0xe5, 0xc7, 0xc2, 0x85, 0x3f, 0xc0, 0xf4, 0x63, 0xe2, 0x8c, 0x32, 0xbb,
	0x73, 0xde, 0x3e, 0xef, 0x7b, 0xce, 0x69, 0x0b, 0x15, 0x61, 0xbb, 0xcd, 0x19, 0x1b, 0x2d, 0xfd,
	0x59, 0x73, 0x7d, 0x96, 0x54, 0xea, 0x8a, 0x7b, 0xbe, 0x87, 0xee, 0x0b, 0xdb, 0x55, 0x13, 0x65,
	0x7d, 0x56, 0xeb, 0xc1, 0x31, 0x61, 0x2b, 0x8f, 0xfb, 0x5a, 0xc0, 0x39, 0x73, 0xfd, 0xf3, 0xa5,
	0x37, 0x59, 0xe0, 0xc0, 0x19, 0x33, 0x4e, 0xd8, 0xfb, 0x80, 0x09, 0x1f, 0x95, 0x21, 0xc7, 0x23,
	0x44, 0x96, 0xaa, 0x52, 0xe3, 0x80, 0x24, 0x1d, 0x2a, 0x41, 0x46, 0xcc, 0x6d, 0x39, 0x1d, 0x89,
	0x61, 0x59, 0xfb, 0x25, 0x81, 0xbc, 0x2f, 0x27, 0xc2, 0x1f, 0x43, 0xc1, 0x9f, 0x3b, 0x4c, 0xf8,
	0x23, 0x67, 0x15, 0x25, 0x65, 0xc9, 0x5f, 0x01, 0x0d, 0x01, 0xc6, 0xa1, 0x85, 0xba, 0x81, 0x23,
	0xe4, 0x74, 0x35, 0xd3, 0x28, 0xb6, 0x9e, 0xab, 0xb7, 0x76, 0x55, 0xef, 0x8a, 0x56, 0xaf, 0x15,
	0x61, 0xb8, 0x3e, 0xdf, 0x90, 0xc2, 0xf8, 0xba, 0x47, 0x4f, 0xe0, 0x40, 0xd8, 0xee, 0x94, 0xae,
	0x19, 0x17, 0x73, 0xcf, 0x95, 0x33, 0x55, 0xa9, 0x51, 0x20, 0xc5, 0x50, 0x7b, 0x1b, 0x4b, 0x95,
	0x57, 0x70, 0x78, 0xdb, 0x1f, 0x1e, 0xb6, 0x60, 0x9b, 0x68, 0xc7, 0x02, 0x09, 0x4b, 0x74, 0x04,
	0xf7, 0xd6, 0xa3, 0x65, 0xc0, 0xa2, 0x63, 0xb3, 0x24, 0x6e, 0x5e, 0xa6, 0x5f, 0x48, 0xb5, 0x1e,
	0x54, 0xef, 0x7e, 0x7f, 0x62, 0xe5, 0xb9, 0x82, 0xa1, 0x3a, 0x64, 0x18, 0xe7, 0x51, 0x5e, 0xb1,
	0xf5, 0xf0, 0x9f, 0xa3, 0x0c, 0xce, 0xfb, 0xc2, 0x26, 0x21, 0x51, 0xeb, 0x40, 0x2e, 0x6e, 0xd1,
	0x09, 0x64, 0x27, 0xde, 0x94, 0x45, 0x9e, 0xc3, 0x56, 0xf9, 0x7f, 0x8f, 0xe6, 0x4d, 0x19, 0x89,
	0x98, 0x70, 0x5d, 0x47, 0xc4, 0xdf, 0xa1, 0x40, 0xc2, 0xf2, 0xe4, 0xb3, 0x04, 0xf9, 0x84, 0x41,
	0x32, 0x1c, 0x19, 0x84, 0x58, 0x84, 0x6a, 0x96, 0x6e, 0xd0, 0x21, 0xd6, 0x8d, 0x8e, 0x89, 0x0d,
	0xbd, 0x94, 0x42, 0x65, 0x78, 0x70, 0xe3, 0x89, 0x66, 0xf5, 0xfb, 0x16, 0x2e, 0xfd, 0xce, 0xa0,
	0x2a, 0x3c, 0x8a, 0x75, 0x6c, 0xd1, 0x81, 0xd5, 0x33, 0x30, 0xb5, 0x30, 0xd5, 0x2f, 0x06, 0x54,
	0xeb, 0xb6, 0x4d, 0x5c, 0xfa, 0x96, 0xdf, 0x4f, 0x5c, 0x10, 0x2d, 0x21, 0xbe, 0xe7, 0xd1, 0x31,
	0x54, 0x62, 0xc2, 0xc4, 0xe6, 0x80, 0x5e, 0x9a, 0x83, 0xae, 0x4e, 0xda, 0x97, 0xb4, 0xd3, 0x36,
	0xdf, 0x18, 0x7a, 0xe9, 0x47, 0x1e, 0x3d, 0x85, 0xfa, 0x8d, 0xe1, 0xd8, 0xa2, 0x06, 0xb6, 0x86,
	0xaf, 0xbb, 0xfb, 0x06, 0xfe, 0xcc, 0x9f, 0xb7, 0x3f, 0x6d, 0x15, 0xe9, 0x6a, 0xab, 0x48, 0x5f,
	0xb7, 0x8a, 0xf4, 0x71, 0xa7, 0xa4, 0xae, 0x76, 0x4a, 0xea, 0xcb, 0x4e, 0x49, 0xbd, 0xab, 0xdb,
	0x73, 0x7f, 0x16, 0x8c, 0xd5, 0x89, 0xe7, 0x34, 0x27, 0x6c, 0xc9, 0xf8, 0xa9, 0xcb, 0xfc, 0x0f,
	0x1e, 0x5f, 0x34, 0x85, 0xed, 0x9e, 0xae, 0x5b, 0x4d, 0xce, 0x96, 0xa3, 0x0d, 0xe3, 0xe3, 0x5c,
	0xf4, 0xfb, 0x3f, 0xfb, 0x13, 0x00, 0x00, 0xff, 0xff, 0xc7, 0xa8, 0x29, 0x8e, 0x1c, 0x03, 0x00,
	0x00,
}

func (m *ReportCurrentBlockNumberRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ReportCurrentBlockNumberRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ReportCurrentBlockNumberRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Sig) > 0 {
		i -= len(m.Sig)
		copy(dAtA[i:], m.Sig)
		i = encodeVarintHealth(dAtA, i, uint64(len(m.Sig)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Report) > 0 {
		i -= len(m.Report)
		copy(dAtA[i:], m.Report)
		i = encodeVarintHealth(dAtA, i, uint64(len(m.Report)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CurrentBlockNumberReport) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CurrentBlockNumberReport) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CurrentBlockNumberReport) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SgndVersion) > 0 {
		i -= len(m.SgndVersion)
		copy(dAtA[i:], m.SgndVersion)
		i = encodeVarintHealth(dAtA, i, uint64(len(m.SgndVersion)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.BlockNums) > 0 {
		for k := range m.BlockNums {
			v := m.BlockNums[k]
			baseI := i
			i = encodeVarintHealth(dAtA, i, uint64(v))
			i--
			dAtA[i] = 0x10
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintHealth(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintHealth(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Timestamp != 0 {
		i = encodeVarintHealth(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ReportCurrentBlockNumberResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ReportCurrentBlockNumberResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ReportCurrentBlockNumberResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Err != nil {
		{
			size, err := m.Err.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintHealth(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ErrMsg) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ErrMsg) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ErrMsg) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Msg) > 0 {
		i -= len(m.Msg)
		copy(dAtA[i:], m.Msg)
		i = encodeVarintHealth(dAtA, i, uint64(len(m.Msg)))
		i--
		dAtA[i] = 0x12
	}
	if m.Code != 0 {
		i = encodeVarintHealth(dAtA, i, uint64(m.Code))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintHealth(dAtA []byte, offset int, v uint64) int {
	offset -= sovHealth(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ReportCurrentBlockNumberRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Report)
	if l > 0 {
		n += 1 + l + sovHealth(uint64(l))
	}
	l = len(m.Sig)
	if l > 0 {
		n += 1 + l + sovHealth(uint64(l))
	}
	return n
}

func (m *CurrentBlockNumberReport) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Timestamp != 0 {
		n += 1 + sovHealth(uint64(m.Timestamp))
	}
	if len(m.BlockNums) > 0 {
		for k, v := range m.BlockNums {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovHealth(uint64(len(k))) + 1 + sovHealth(uint64(v))
			n += mapEntrySize + 1 + sovHealth(uint64(mapEntrySize))
		}
	}
	l = len(m.SgndVersion)
	if l > 0 {
		n += 1 + l + sovHealth(uint64(l))
	}
	return n
}

func (m *ReportCurrentBlockNumberResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Err != nil {
		l = m.Err.Size()
		n += 1 + l + sovHealth(uint64(l))
	}
	return n
}

func (m *ErrMsg) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Code != 0 {
		n += 1 + sovHealth(uint64(m.Code))
	}
	l = len(m.Msg)
	if l > 0 {
		n += 1 + l + sovHealth(uint64(l))
	}
	return n
}

func sovHealth(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozHealth(x uint64) (n int) {
	return sovHealth(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ReportCurrentBlockNumberRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHealth
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ReportCurrentBlockNumberRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ReportCurrentBlockNumberRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Report", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHealth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthHealth
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthHealth
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Report = append(m.Report[:0], dAtA[iNdEx:postIndex]...)
			if m.Report == nil {
				m.Report = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sig", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHealth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthHealth
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthHealth
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sig = append(m.Sig[:0], dAtA[iNdEx:postIndex]...)
			if m.Sig == nil {
				m.Sig = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipHealth(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthHealth
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CurrentBlockNumberReport) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHealth
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CurrentBlockNumberReport: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CurrentBlockNumberReport: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHealth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockNums", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHealth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthHealth
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthHealth
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BlockNums == nil {
				m.BlockNums = make(map[string]uint64)
			}
			var mapkey string
			var mapvalue uint64
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowHealth
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowHealth
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthHealth
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthHealth
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowHealth
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipHealth(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthHealth
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.BlockNums[mapkey] = mapvalue
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SgndVersion", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHealth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHealth
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthHealth
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SgndVersion = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipHealth(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthHealth
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ReportCurrentBlockNumberResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHealth
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ReportCurrentBlockNumberResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ReportCurrentBlockNumberResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Err", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHealth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthHealth
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthHealth
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Err == nil {
				m.Err = &ErrMsg{}
			}
			if err := m.Err.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipHealth(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthHealth
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ErrMsg) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHealth
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ErrMsg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ErrMsg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			m.Code = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHealth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Code |= ErrCode(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msg", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHealth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHealth
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthHealth
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Msg = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipHealth(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthHealth
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipHealth(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowHealth
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowHealth
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowHealth
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthHealth
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupHealth
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthHealth
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthHealth        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowHealth          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupHealth = fmt.Errorf("proto: unexpected end of group")
)
