# Build and publish release binaries, on v* tag

name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v3
        with:
          go-version: ^1.18
      - name: Configure git for private repo
        run: |
          export GOPRIVATE=github.com/celer-network/cbridge-flow
          git config --global url."https://${{ secrets.GH_TOKEN }}:@github.com/".insteadOf "https://github.com/"
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get version tag
        id: get_tag
        run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}
      - name: Setup dependencies
        run: |
          sudo apt update && sudo apt install gcc make
          sudo apt install libleveldb-dev
      - name: Build and tar
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          # sgnd-cleveldb-ubuntu-linux-amd64
          GOOS=linux GOARCH=amd64 WITH_CLEVELDB=yes make install
          tar czfC sgnd-${{ steps.get_tag.outputs.TAG }}-cleveldb-ubuntu-linux-amd64.tar.gz $HOME/go/bin sgnd
          # sgnd-goleveldb-linux-amd64
          GOOS=linux GOARCH=amd64 make install
          tar czfC sgnd-${{ steps.get_tag.outputs.TAG }}-goleveldb-linux-amd64.tar.gz $HOME/go/bin sgnd
          # sgnd-goleveldb-linux-arm64
          GOOS=linux GOARCH=arm64 make install
          tar czfC sgnd-${{ steps.get_tag.outputs.TAG }}-goleveldb-linux-arm64.tar.gz $HOME/go/bin sgnd
          # aws-kms-tools-linux-amd64
          GOOS=linux GOARCH=amd64 go build -o $HOME/go/bin/aws-kms-tools tools/aws-kms-tools/main.go
          tar czfC aws-kms-tools-${{ steps.get_tag.outputs.TAG }}-linux-amd64.tar.gz $HOME/go/bin aws-kms-tools
          # aws-kms-tools-linux-arm64
          GOOS=linux GOARCH=arm64 go build -o $HOME/go/bin/aws-kms-tools tools/aws-kms-tools/main.go
          tar czfC aws-kms-tools-${{ steps.get_tag.outputs.TAG }}-linux-arm64.tar.gz $HOME/go/bin aws-kms-tools
          # aws-kms-tools-darwin-amd64
          GOOS=darwin GOARCH=amd64 go build -o $HOME/go/bin/aws-kms-tools tools/aws-kms-tools/main.go
          tar czfC aws-kms-tools-${{ steps.get_tag.outputs.TAG }}-darwin-amd64.tar.gz $HOME/go/bin aws-kms-tools
          # aws-kms-tools-darwin-arm64
          GOOS=darwin GOARCH=arm64 go build -o $HOME/go/bin/aws-kms-tools tools/aws-kms-tools/main.go
          tar czfC aws-kms-tools-${{ steps.get_tag.outputs.TAG }}-darwin-arm64.tar.gz $HOME/go/bin aws-kms-tools
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            sgnd-${{ steps.get_tag.outputs.TAG }}-cleveldb-ubuntu-linux-amd64.tar.gz
            sgnd-${{ steps.get_tag.outputs.TAG }}-goleveldb-linux-amd64.tar.gz
            sgnd-${{ steps.get_tag.outputs.TAG }}-goleveldb-linux-arm64.tar.gz
            aws-kms-tools-${{ steps.get_tag.outputs.TAG }}-linux-amd64.tar.gz
            aws-kms-tools-${{ steps.get_tag.outputs.TAG }}-linux-arm64.tar.gz
            aws-kms-tools-${{ steps.get_tag.outputs.TAG }}-darwin-amd64.tar.gz
            aws-kms-tools-${{ steps.get_tag.outputs.TAG }}-darwin-arm64.tar.gz
