name: Run singlenode tests

on: [pull_request]

jobs:
  run-singlenode-tests:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          src:
            - '.github/workflows/run_singlenode_tests.yml'
            - 'app/**'
            - 'cmd/**'
            - 'common/**'
            - 'eth/**'
            - 'networks/**'
            - 'proto/**'
            - 'relayer/**'
            - 'scripts/**'
            - 'seal/**'
            - 'test/**'
            - 'transactor/**'
            - 'x/**'
            - 'go.mod'
            - 'go.sum'
            - 'Makefile'
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17'
    - name: Install dependencies
      if: steps.filter.outputs.src == 'true'
      run: |
        sudo apt install gcc make git libleveldb-dev
    - name: Download geth
      if: steps.filter.outputs.src == 'true'
      run: |
        source scripts/download.sh
        download_geth
    - name: go vet source code
      if: steps.filter.outputs.src == 'true'
      run: |
        go vet ./...
    - name: Check gofmt
      if: steps.filter.outputs.src == 'true'
      run: |
        gofmt -l . | awk '{c++; print} END {exit c}'
    - name: Run singlenode tests
      if: steps.filter.outputs.src == 'true'
      run: |
        go test -failfast -v -timeout 30m github.com/celer-network/sgn-v2/test/e2e/singlenode
