name: Run singlenode tests

on: [pull_request]

jobs:
  run-singlenode-tests:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17'
    - name: Install dependencies
      run: |
        sudo apt install gcc make git libleveldb-dev
    - name: Download geth
      run: |
        source scripts/download.sh
        download_geth
    - name: go vet source code
      run: |
        go vet ./...
    - name: Check gofmt
      run: |
        gofmt -l . | awk '{c++; print} END {exit c}'
    - name: Run singlenode tests
      run: |
        go test -failfast -v -timeout 30m github.com/celer-network/sgn-v2/test/e2e/singlenode
